# Generated by Django 5.2.8 on 2025-12-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stundent",
        ),
    ]
