# Generated by Django 5.2.8 on 2025-12-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(help_text="Patient full name", max_length=150),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=30,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Patient date of birth (YYYY-MM-DD)"),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        help_text="Clinician assigned to this assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_as_clinician",
                        to="accounts.profile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student assigned to this assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_as_student",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
