# Generated by Django 5.2.8 on 2025-12-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="phone",
        ),
        migrations.AlterField(
            model_name="assessments",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="evaluator",
            field=models.ForeignKey(
                help_text="Assigned evaluator",
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluator_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="student",
            field=models.ForeignKey(
                help_text="Assigned student",
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_assessments",
                to="accounts.profile",
            ),
        ),
    ]
