# Generated by Django 5.2.8 on 2025-12-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0002_remove_assessments_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="aggravating_factors",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="associated_symptoms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="cerebellar",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="chief_complaint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="cranial_nerves",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="diastolic_bp",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Diastolic BP (mmHg)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="diet",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="family_hx",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="further_diagnostic_procedures",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="health_hx_review",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="history_of_condition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="imaging",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="inspection_gait",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="inspection_posture",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="inspection_regional",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="instrumentation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_section_1_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_section_2_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_section_3_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_student_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="lab",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="nerve_root",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="occupational",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="orthopedic_assessment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="pain",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="palpation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="past_illnesses",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="pathological",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="percussion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="peripheral",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="procedures_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="procedures_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_signed_sections",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="psycho_social_hx",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="ptt",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="assessments",
            name="pulse",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="relieving_factors",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="respiratory",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="rom_active",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="rom_passive",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="rom_resisted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="second_chiropractic_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_1_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_1_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section1_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_2_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_2_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section2_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_3_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_3_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section3_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="special_direction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="special_examination_instruction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="spinal_cord",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="student_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="student_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="system_review",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="systolic_bp",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Systolic BP (mmHg)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="third_chiropractic_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="evaluator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluator_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="patient_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_assessments",
                to="accounts.profile",
            ),
        ),
    ]
