# Generated by Django 5.2.8 on 2026-01-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0003_assessments_aggravating_factors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="is_student_signed",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="student_signed_at",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="student_signed_by",
        ),
        migrations.AddField(
            model_name="assessments",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="diagnosis",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="differential_diagnosis",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_consent_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessments/patient_signatures/"
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_consent_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_consent_signed_by",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_initial_patient_consent_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_section_4_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_section_5_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="phase_1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="phase_2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="phase_3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_4_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_4_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section4_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_5_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_5_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section5_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="working_diagnosis",
            field=models.TextField(blank=True, default=""),
        ),
    ]
