# Generated by Django 5.2.8 on 2026-01-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_remove_assessments_is_student_signed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="date",
            new_name="diagnosis_date",
        ),
    ]
