# Generated by Django 5.2.8 on 2026-01-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0005_rename_date_assessments_diagnosis_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assessments",
                to="accounts.profile",
            ),
        ),
    ]
