# Generated by Django 5.2.8 on 2026-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_assessments_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="file_number",
            field=models.CharField(default="IMU000000001", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_discharged",
            field=models.BooleanField(default=False),
        ),
    ]
