# Generated by Django 5.2.8 on 2026-01-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_assessments_file_number_assessments_is_discharged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="initial_patient_consent_signed_by",
        ),
        migrations.AddField(
            model_name="assessments",
            name="education_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="marketing_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="research_consent",
            field=models.BooleanField(default=False),
        ),
    ]
