# Generated by Django 5.2.8 on 2026-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0008_remove_assessments_initial_patient_consent_signed_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="treatment_remarks",
            field=models.TextField(blank=True, default=""),
        ),
    ]
