# Generated by Django 5.2.8 on 2026-02-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_assessments_treatment_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="is_section_5_signed",
            new_name="is_treatment_plan_complete",
        ),
    ]
