# Generated by Django 5.2.8 on 2026-02-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0010_rename_is_section_5_signed_assessments_is_treatment_plan_complete",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="is_treatment_plan_complete",
            new_name="is_treatment_plan_signed",
        ),
        migrations.RenameField(
            model_name="assessments",
            old_name="section_5_signed_at",
            new_name="treatment_plan_signed_at",
        ),
        migrations.RenameField(
            model_name="assessments",
            old_name="section_5_signed_by",
            new_name="treatment_plan_signed_by",
        ),
    ]
