# Generated by Django 5.2.8 on 2026-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0011_rename_is_treatment_plan_complete_assessments_is_treatment_plan_signed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="contraindications",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="red_flags",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="yellow_flags",
            field=models.TextField(blank=True, default=""),
        ),
    ]
