# Generated by Django 5.2.8 on 2026-03-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0012_assessments_contraindications_assessments_red_flags_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="procedures_signed_at",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="procedures_signed_by",
        ),
    ]
