# Generated by Django 5.2.8 on 2026-03-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0013_remove_assessments_procedures_signed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="further_diagnostic_procedures",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="ptt",
        ),
    ]
