# Generated by Django 5.2.8 on 2026-03-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0014_remove_assessments_further_diagnostic_procedures_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="second_chiropractic_notes",
            new_name="first_chiropractic",
        ),
        migrations.RenameField(
            model_name="assessments",
            old_name="third_chiropractic_notes",
            new_name="second_chiropractic",
        ),
    ]
