# Generated by Django 5.2.8 on 2026-03-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0015_rename_second_chiropractic_notes_assessments_first_chiropractic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="discharge_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessments",
            name="reason_for_discharge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discharged_full_recovery", "Discharged - Full Recovery"),
                    (
                        "patient_discharged_against_advice",
                        "Patient Discharged Against Advice",
                    ),
                    ("lost_to_follow_up", "Lost to Follow-up"),
                    ("referred_to_physician", "Referred to Physician"),
                    ("transferred_to_another_Intern", "Transferred to Another Intern"),
                    (
                        "transferred_to_community_chiropractor",
                        "Transferred to Community Chiropractor",
                    ),
                    ("moved_away", "Moved Away"),
                    ("deceased", "Deceased"),
                ],
                default="discharged_full_recovery",
                max_length=50,
            ),
        ),
    ]
