# Generated by Django 5.2.8 on 2026-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0016_assessments_discharge_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="reason_for_discharge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discharged_full_recovery", "Discharged - Full Recovery"),
                    (
                        "patient_discharged_against_advice",
                        "Patient Discharged Against Advice",
                    ),
                    ("lost_to_follow_up", "Lost to Follow-up"),
                    ("referred_to_physician", "Referred to Physician"),
                    ("transferred_to_another_Intern", "Transferred to Another Intern"),
                    (
                        "transferred_to_community_chiropractor",
                        "Transferred to Community Chiropractor",
                    ),
                    ("moved_away", "Moved Away"),
                    ("deceased", "Deceased"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
