# Generated by Django 5.2.8 on 2026-03-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0017_alter_assessments_reason_for_discharge"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoapModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("ifc", "IFC"),
                            ("pre_mod", "Pre Mod"),
                            ("tens", "TENS"),
                            ("micro_russ_us_combo", "Micro Russ US Combo"),
                            ("laser", "Laser"),
                            ("traction", "Traction"),
                            ("fd", "FD"),
                            ("shockwave", "Shockwave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.TextField(blank=True, default="")),
                ("settings", models.TextField(blank=True, default="")),
                ("duration_intensity", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "SOAP Modality",
                "verbose_name_plural": "SOAP Modalities",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Soaps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soap_pulse", models.PositiveSmallIntegerField()),
                ("soap_respiratory", models.PositiveSmallIntegerField()),
                (
                    "soap_systolic_bp",
                    models.PositiveSmallIntegerField(
                        help_text="S.O.A.P. Systolic BP (mmHg)"
                    ),
                ),
                (
                    "soap_diastolic_bp",
                    models.PositiveSmallIntegerField(
                        help_text="S.O.A.P. Diastolic BP (mmHg)"
                    ),
                ),
                ("subjective", models.TextField(blank=True, default="")),
                ("objective", models.TextField(blank=True, default="")),
                ("soap_assessment", models.TextField(blank=True, default="")),
                ("plan", models.TextField(blank=True, default="")),
                (
                    "mp_smt",
                    models.ImageField(
                        blank=True, null=True, upload_to="assessments/soap_mp_smt/"
                    ),
                ),
                (
                    "patient_tolerated_treatment_well",
                    models.BooleanField(default=False),
                ),
                ("patient_improved_with_treatment", models.BooleanField(default=False)),
                ("pain_after_treatment", models.BooleanField(default=False)),
                ("adverse_reactions_to_treatment", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, default="")),
                ("next_appointment", models.DateField()),
                ("is_soap_signed", models.BooleanField(default=False)),
                (
                    "soap_signed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SOAP Note",
                "verbose_name_plural": "SOAP Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="assessments",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.AlterField(
            model_name="assessments",
            name="reason_for_discharge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discharged_full_recovery", "Discharged - Full Recovery"),
                    (
                        "patient_discharged_against_advice",
                        "Patient Discharged Against Advice",
                    ),
                    ("lost_to_follow_up", "Lost to Follow-up"),
                    ("referred_to_physician", "Referred to Physician"),
                    ("transferred_to_another_Intern", "Transferred to Another Intern"),
                    (
                        "transferred_to_community_chiropractor",
                        "Transferred to Community Chiropractor",
                    ),
                    ("moved_away", "Moved Away"),
                    ("deceased", "Deceased"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="assessments",
            index=models.Index(
                fields=["file_number"], name="assessments_file_nu_697a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessments",
            index=models.Index(
                fields=["patient_name"], name="assessments_patient_3e4ea7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessments",
            index=models.Index(
                fields=["created_at"], name="assessments_created_3036b6_idx"
            ),
        ),
        migrations.AddField(
            model_name="soaps",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soaps",
                to="assessments.assessments",
            ),
        ),
        migrations.AddField(
            model_name="soaps",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_soaps",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="soaps",
            name="soap_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="soap_signed",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="soaps",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_soaps",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="soapmodality",
            name="soap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soap_modalities",
                to="assessments.soaps",
            ),
        ),
        migrations.AddIndex(
            model_name="soaps",
            index=models.Index(
                fields=["assessment"], name="assessments_assessm_4a3da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soaps",
            index=models.Index(
                fields=["created_at"], name="assessments_created_b39ce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soaps",
            index=models.Index(
                fields=["next_appointment"], name="assessments_next_ap_37b970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soapmodality",
            index=models.Index(fields=["soap"], name="assessments_soap_id_368bb7_idx"),
        ),
        migrations.AddIndex(
            model_name="soapmodality",
            index=models.Index(
                fields=["modality"], name="assessments_modalit_b67ffe_idx"
            ),
        ),
    ]
