# Generated by Django 5.2.8 on 2026-03-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0018_soapmodality_soaps_alter_assessments_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soaps",
            old_name="remarks",
            new_name="notes",
        ),
    ]
