# Generated by Django 5.2.8 on 2026-04-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0019_rename_remarks_soaps_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="soaps",
            name="evaluator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluator_soaps",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="soaps",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_soap",
                to="accounts.profile",
            ),
        ),
    ]
