# Generated by Django 5.2.8 on 2026-04-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0020_soaps_evaluator_soaps_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soaps",
            name="evaluator",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "clinician"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluator_soaps",
                to="accounts.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="soaps",
            name="student",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_soap",
                to="accounts.profile",
            ),
            preserve_default=False,
        ),
    ]
