# Generated by Django 5.2.8 on 2026-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0021_alter_soaps_evaluator_alter_soaps_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soaps",
            name="next_appointment",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
