# Generated by Django 5.2.8 on 2026-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0022_alter_soaps_next_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="rom_drawing",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessments/rom_drawings/"
            ),
        ),
    ]
