# Generated by Django 5.2.8 on 2026-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0023_assessments_rom_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="soaps",
            name="markers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
