# Generated by Django 5.2.8 on 2026-05-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0024_soaps_markers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soaps",
            name="mp_smt",
        ),
        migrations.AddField(
            model_name="assessments",
            name="section_1_anatomy_markers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
