# Generated by Django 5.2.8 on 2026-05-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0025_remove_soaps_mp_smt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientReevaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_reevaluation",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("current_status", models.TextField(blank=True, default="")),
                ("physical_examination", models.TextField(blank=True, default="")),
                ("diagnosis", models.TextField(blank=True, default="")),
                ("treatment_plan", models.TextField(blank=True, default="")),
                ("outcome_measures", models.TextField(blank=True, default="")),
                (
                    "next_reevaluation",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("is_reevaluation_signed", models.BooleanField(default=False)),
                (
                    "reevaluation_signed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_reevaluations",
                        to="assessments.assessments",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_reevaluations",
                        to="accounts.profile",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        limit_choices_to={"role": "clinician"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluator_patient_reevaluations",
                        to="accounts.profile",
                    ),
                ),
                (
                    "reevaluation_signed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        limit_choices_to={"role": "clinician"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reevaluation_signed",
                        to="accounts.profile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_patient_reevaluations",
                        to="accounts.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_patient_reevaluations",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Reevaluation",
                "verbose_name_plural": "Patient Reevaluations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assessment"], name="assessments_assessm_04ddc6_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="assessments_created_08e9ba_idx"
                    ),
                    models.Index(
                        fields=["next_reevaluation"],
                        name="assessments_next_re_04ce94_idx",
                    ),
                ],
            },
        ),
    ]
