# Generated by Django 5.2.8 on 2026-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0027_patientnewcomplaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="intervention_approved",
            field=models.TextField(blank=True, default=""),
        ),
    ]
