# Generated by Django 5.2.8 on 2026-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0028_assessments_intervention_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="attending_consent_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessments/attending_signatures/"
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="attending_consent_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_attending_consent_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_pdpa_consent_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_witness_consent_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="pdpa_consent_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessments/pdpa_signatures/"
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="pdpa_consent_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="witness_consent_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessments/witness_signatures/"
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="witness_consent_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
