# Generated by Django 5.2.8 on 2026-05-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
        ("assessments", "0029_assessments_attending_consent_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="attending_consent_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": ["clinician", "student"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attending_consent_signed_assessments",
                to="accounts.profile",
            ),
        ),
    ]
