# Generated by Django 5.2.8 on 2026-05-28 09:23

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0030_assessments_attending_consent_signed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="witness_consent_signed_by",
            field=models.CharField(default="Test", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessments",
            name="attending_consent_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=assessments.models.AssessmentUploadPath(
                    "attending_signatures"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="initial_patient_consent_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=assessments.models.AssessmentUploadPath("patient_signatures"),
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="pdpa_consent_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=assessments.models.AssessmentUploadPath("pdpa_signatures"),
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="rom_drawing",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=assessments.models.AssessmentUploadPath("rom_drawing"),
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="witness_consent_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=assessments.models.AssessmentUploadPath("witness_signatures"),
            ),
        ),
    ]
