# Generated by Django 5.2.8 on 2026-05-29 09:20

import assessments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_options"),
        ("assessments", "0032_alter_assessments_attending_consent_signed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=assessments.models.AssessmentUploadPath("attachments")
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="assessments.assessments",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
