# Generated by Django 5.2.8 on 2026-05-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_options"),
        ("assessments", "0033_assessmentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="discharge_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="discharge_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discharge_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="treatment_plan_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatment_plan_signed_assessments",
                to="accounts.profile",
            ),
        ),
    ]
