# Generated by Django 5.2.8 on 2026-06-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0034_assessments_discharge_signed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="orthopedic_assessment",
            new_name="orthopaedic_assessment",
        ),
    ]
