# Generated by Django 5.2.8 on 2026-06-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0035_rename_orthopedic_assessment_assessments_orthopaedic_assessment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_signed_by",
            field=models.CharField(default="Test Patient Consent name", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessments",
            name="pdpa_consent_signed_by",
            field=models.CharField(default="Test PDPA Consent Name", max_length=150),
            preserve_default=False,
        ),
    ]
