# Generated by Django 5.2.8 on 2026-06-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0036_assessments_initial_patient_signed_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="initial_patient_signed_by",
            new_name="initial_patient_consent_signed_by",
        ),
    ]
