# Generated by Django 5.2.8 on 2026-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0037_rename_initial_patient_signed_by_assessments_initial_patient_consent_signed_by",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="chiropractic_intern_treatment_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="patient_record_review_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="student_observation_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessments",
            name="treatment_discontinuation_policy_consent",
            field=models.BooleanField(default=False),
        ),
    ]
