# Generated by Django 5.2.8 on 2026-06-18 07:21

from django.db import migrations


def set_existing_records_to_true(apps, schema_editor):
    Assessments = apps.get_model("assessments", "Assessments")  # replace with your model

    Assessments.objects.all().update(
        patient_record_review_consent=True,
        treatment_discontinuation_policy_consent=True,
        student_observation_consent=True,
        chiropractic_intern_treatment_consent=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0038_assessments_chiropractic_intern_treatment_consent_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_existing_records_to_true,
            migrations.RunPython.noop,
        ),
    ]