# Generated by Django 5.2.8 on 2026-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0039_populate_consent_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="interpreter_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="assessments",
            name="witness_relationship",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("spouse", "Spouse"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("sibling", "Sibling"),
                    ("guardian", "Legal Guardian"),
                    ("caregiver", "Caregiver"),
                    ("next_of_kin", "Next of Kin"),
                    ("relative", "Other Relative"),
                    ("friend", "Friend"),
                    ("employer", "Employer"),
                    ("colleague", "Colleague"),
                    ("legal_representative", "Legal Representative"),
                    ("power_of_attorney", "Power of Attorney"),
                    ("healthcare_proxy", "Healthcare Proxy"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="self",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
