# Generated by Django 5.2.8 on 2026-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0040_assessments_interpreter_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="education_consent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="is_pdpa_consent_signed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="marketing_consent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="pdpa_consent_signed_by",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="research_consent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
