# Generated by Django 5.2.8 on 2026-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_address_4"),
        ("assessments", "0041_alter_assessments_education_consent_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assessments",
            name="assessments_file_nu_697a17_idx",
        ),
        migrations.RenameField(
            model_name="assessments",
            old_name="file_number",
            new_name="mrn_number",
        ),
        migrations.AlterField(
            model_name="assessments",
            name="witness_relationship",
            field=models.CharField(
                choices=[
                    ("supervising_clinician", "Supervising Clinician"),
                    ("staff_nurse", "Staff Nurse"),
                    ("healthcare_professional", "Healthcare Professional"),
                    ("colleague", "Colleague"),
                    ("student_peer", "Student Peer"),
                    ("administrative_staff", "Administrative Staff"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="assessments",
            index=models.Index(
                fields=["mrn_number"], name="assessments_mrn_num_5c517b_idx"
            ),
        ),
    ]
