# Generated by Django 5.2.8 on 2026-06-22 08:28

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0042_remove_assessments_assessments_file_nu_697a17_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="ic_passport_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
    ]
