# Generated by Django 5.2.8 on 2026-06-22 08:33

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0043_assessments_ic_passport_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="ic_passport_number",
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
    ]
