# Generated by Django 5.2.8 on 2026-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0044_alter_assessments_ic_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="ic_passport_hash",
            field=models.CharField(
                db_index=True,
                default=2323232323324234234,
                editable=False,
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
