# Generated by Django 5.2.8 on 2026-06-23

from django.db import migrations


def populate_fake_ic_numbers(apps, schema_editor):
    Assessments = apps.get_model("assessments", "Assessments")

    # Only update records missing IC/passport number
    assessments = Assessments.objects.filter(
        ic_passport_number__isnull=True
    )

    counter = 1

    for assessment in assessments:
        assessment.ic_passport_number = f"FAKE-IC-{assessment.id:06d}"
        assessment.save(update_fields=["ic_passport_number"])
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0045_assessments_ic_passport_hash"),
    ]

    operations = [
        migrations.RunPython(
            populate_fake_ic_numbers,
            migrations.RunPython.noop,
        ),
    ]