# Generated by Django 5.2.8 on 2026-06-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_address_4"),
        ("assessments", "0047_fix_empty_ic_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="consent_section_signed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assessments",
            name="consent_section_signed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": "clinician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_signed_assessments",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="is_consent_section_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="initial_patient_consent_signed_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="witness_consent_signed_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="witness_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supervising_clinician", "Supervising Clinician"),
                    ("staff_nurse", "Staff Nurse"),
                    ("healthcare_professional", "Healthcare Professional"),
                    ("colleague", "Colleague"),
                    ("student_peer", "Student Peer"),
                    ("administrative_staff", "Administrative Staff"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
