# Generated by Django 5.2.8 on 2026-06-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0048_assessments_consent_section_signed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="witness_relationship",
            new_name="initial_patient_consent_relationship",
        ),
    ]
