# Generated by Django 5.2.8 on 2026-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0049_rename_witness_relationship_assessments_initial_patient_consent_relationship",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="ic_passport_number",
            new_name="patient_ic_passport_number",
        ),
        migrations.AlterField(
            model_name="assessments",
            name="initial_patient_consent_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Self (Patient)"),
                    ("parent", "Parent"),
                    ("legal_guardian", "Legal Guardian"),
                    ("spouse", "Spouse"),
                    ("sibling", "Sibling"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("relative", "Other Relative"),
                    ("caregiver", "Caregiver"),
                    ("next_of_kin", "Next of Kin"),
                    ("power_of_attorney", "Power of Attorney"),
                    ("authorized_representative", "Authorized Representative"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
