# Generated by Django 5.2.8 on 2026-06-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0050_rename_ic_passport_number_assessments_patient_ic_passport_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="ic_passport_hash",
            new_name="patient_ic_passport_hash",
        ),
    ]
