# Generated by Django 5.2.8 on 2026-06-24 09:38

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0051_rename_ic_passport_hash_assessments_patient_ic_passport_hash",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_consent_ic_passport_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="assessments",
            name="initial_patient_consent_ic_passport_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
