# Generated by Django 5.2.8 on 2026-07-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profile_transcript_description"),
        (
            "assessments",
            "0052_assessments_initial_patient_consent_ic_passport_hash_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="phase_1",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="phase_2",
        ),
        migrations.RemoveField(
            model_name="assessments",
            name="phase_3",
        ),
        migrations.CreateModel(
            name="AssessmentTreatmentPlanPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_1", models.TextField(blank=True, default="")),
                ("phase_2", models.TextField(blank=True, default="")),
                ("phase_3", models.TextField(blank=True, default="")),
                ("treatment_plan_diagnosis", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plan_phases",
                        to="assessments.assessments",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_treatment_plan_phases",
                        to="accounts.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_treatment_plan_phases",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
