# Generated by Django 5.2.8 on 2026-07-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0053_remove_assessments_phase_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmenttreatmentplanphase",
            options={"ordering": ["-id"]},
        ),
    ]
