# Generated by Django 5.2.8 on 2025-12-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_id",
                    models.CharField(
                        help_text="Unique ID for student or clinician.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("clinician", "Clinician"),
                            ("admin", "Admin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("account_creation_date", models.DateTimeField(auto_now_add=True)),
                ("profile_log", models.TextField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
