# Generated by Django 5.2.8 on 2025-12-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("clinician", "Clinician"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=30,
            ),
        ),
    ]
