# Generated by Django 5.2.8 on 2025-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="official_name",
            field=models.CharField(
                blank=True,
                help_text="Official full name of the user",
                max_length=150,
                null=True,
            ),
        ),
    ]
