# Generated by Django 5.2.8 on 2025-12-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_official_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="official_name",
            field=models.CharField(
                default="Ttemp",
                help_text="Official full name of the user",
                max_length=150,
            ),
            preserve_default=False,
        ),
    ]
