# Generated by Django 5.2.8 on 2026-05-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_official_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["official_name"]},
        ),
    ]
