# Generated by Django 5.2.8 on 2026-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_address_1_profile_address_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nricpsprt",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="IC / Passport"
            ),
        ),
    ]
