# Generated by Django 5.2.8 on 2026-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_profile_unit_code_profile_cohort_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
