# Generated by Django 5.2.8 on 2026-06-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
