# Generated by Django 5.2.8 on 2026-06-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_address_4"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        help_text="Unique code for department.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("department_name", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["department_name"],
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="department_code",
        ),
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinician department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="accounts.department",
            ),
        ),
    ]
