# Generated by Django 5.2.8 on 2026-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_department_remove_profile_department_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_time_password_change",
            field=models.BooleanField(default=True),
        ),
    ]
