# Generated by Django 5.2.8 on 2026-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_first_time_password_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="transcript_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
