"""
Django settings for imu_chiropractic_form project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_NAME = "IMU Chiropractic Form"
APP_VERSION = "0.0.1"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ue5kfsphg74$he6fwzt*7f-cni0%woc^q%&(%)xn(78oet9o1c"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "accounts",
    "students",
    "clinicians",
    "assessments",
    "rest_framework",  # for API
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "imu_chiropractic_form.middleware.LoginRequiredMiddleware",
]

ROOT_URLCONF = "imu_chiropractic_form.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            "students/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "imu_chiropractic_form.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "chiropractic_form_db",
        "USER": "root",
        "PASSWORD": "Admin@imu789!",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # UserAttributeSimilarityValidator → prevents passwords too similar to username/email.
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # MinimumLengthValidator → ensures password is at least 8 characters.
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        # CommonPasswordValidator → prevents simple common passwords.
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        # NumericPasswordValidator → prevents purely numeric passwords.
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        # Custom Validators
        "NAME": "accounts.validators.CustomPasswordValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kuala_Lumpur"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"
STATICFILES_DIRS = []
if DEBUG:
    STATICFILES_DIRS.append(os.path.join(BASE_DIR, "static"))

MEDIA_ROOT = "/imu_chiropractic_form/media/"
MEDIA_URL = "/media/"

STATIC_URL = "static/"

LOGIN_REDIRECT_URL = r"/assessments"
LOGIN_URL = "/login/"
LOGIN_EXEMPT_URLS = (
    r"^login/$",
    r"^login",
    r"^admin/",
    r"^api/*",
    r"^v\d/api/*",
    r"^accounts/api/*",
    r"^media/",
    r"^dashboard/",
    r"^password-reset/",
    r"^forgot-password/",
    r"^onboarding/",
)

# For activity history logs

BASE_LOG_PATH = Path(BASE_DIR) / "logs"
BASE_LOG_PATH.mkdir(exist_ok=True)

ACCOUNTS_LOG_PATH = BASE_LOG_PATH / "accounts"
ACCOUNTS_LOG_PATH.mkdir(parents=True, exist_ok=True)

ASSESSMENTS_LOG_PATH = BASE_LOG_PATH / "assessments"
ASSESSMENTS_LOG_PATH.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "[%(levelname)s] %(asctime)s %(pathname)s:%(lineno)d (%(funcName)s) - %(message)s",
        },
    },
    "handlers": {
        "userprofile_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": ACCOUNTS_LOG_PATH / "userprofile.log",
            "formatter": "default",
        },
        "assessments_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": ASSESSMENTS_LOG_PATH / "assessments.log",
            "formatter": "default",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "loggers": {
        "userprofile": {
            "handlers": ["userprofile_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "assessments": {
            "handlers": ["assessments_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
